import type { Metadata } from "next"; // import Metadata type from next.js. type keyword ensures import is erased at build time(no runtime cost)
import "./globals.css";// import global CSS
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";// imports a custom react component used for Visual editor integratioin and live design editing. 
import ErrorReporter from "@/components/ErrorReporter";// imports path alias(from components)
import Script from "next/script"; // imports <Script /> from Next.js which is more optimized than raw <script> as it allows Controlled script loading prevents blocking rendering 

export const metadata: Metadata = { // exports metadata for all routes
  title: "Create Next App",//Browser tab title 
  description: "Generated by create next app"
};//Metadata is used to Prevent invalid fields and Enable IntelliSense.

export default function RootLayout({ // required default export for a layout.
  children,
}: Readonly<{ //Ensures props cannot be mutated 
  children: React.ReactNode; // Children represents all the nested pages and components.
}>) { 
  return (
    <html lang="en">
      <body className="antialiased"> // antialiased is a tailwind utility which smooths font rendering and improves text clarity
        <Script
          id="orchids-browser-logs" // id is a unique identifier for script management 
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts/orchids-browser-logs.js"
          strategy="afterInteractive" // written so that the script loads after page becomes interactive as it prevents blocking initial render 
          data-orchids-project-id="68e475cf-cf1f-4a70-a881-b091f6d84670" // Custom Data attribute which is opassed to the script in runtime.
        />
        <ErrorReporter /> // makes the error tracking run on the whole page
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE" // Send Messages on navigation events. if someone presses a button in the topbar then this sends the message to where the website should navigate to.
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}' // arbritary JSON data passed to the script
        />
        {children} // THE MOST IMPORTANT LINE IN THE FILE as it contains and renders all of the page.tsx, nested layouts and route components, without this no content page would appear.
        <VisualEditsMessenger /> // used for live visual editing and Overlay UI Route communication Observe rendered content, inject overlays
      </body>
    </html>
  );
}
 